service: aws-serverless-framework
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:scan
            - dynamodb:DeleteItem
          Resource:
            - arn:aws:dynamodb:sa-east-1:875132407844:table/ItemTableNew

functions:
  api:
    handler: src/item/index.handler
    events:
      - http:
          path: /
          method: get
  insertItem:
    handler: src/item/insertItem.handler
    events:
      - http:
          path: /item
          method: post
  fetchItems:
    handler: src/item/fetchItems.handler
    events:
      - http:
          path: /items
          method: get
  fetchItem:
    handler: src/item/fetchItem.handler
    events:
      - http:
          path: /item/{id}
          method: get
  updateItem:
    handler: src/item/updateItem.handler
    events:
      - http:
          path: /item/{id}
          method: put
  removeItem:
    handler: src/item/removeItem.handler
    events:
      - http:
          path: /item/{id}
          method: delete

resources:
  Resources:
    ItemTableNew:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ItemTableNew
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    Tasks:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Tasks
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          